server:
  servlet:
    context-path: /api/preorder

spring:
  application:
    name: java-course-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/preorder?currentSchema=order_schema
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: smtp.mail.ru
    port: 587
    username: orange.preorder@mail.ru
    password: 0kqdRAEpDrsNta1Fs98E
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  name: @project.artifactId@
  version: @project.version@

app:
  time-zone: Europe/Chisinau

restaurant:
  resources:
    path: classpath:/images/


jwt.secret: 470d677417ed8f552f69e14d363850291654e8484161fd171a37676e848f7ffb
jwt:
    expiration-time: 360000